#! /usr/bin/python

import argparse
import re
import datetime
import os

from LIB_STRT_DoStartUp import StartUp
from LIB_SSH import SSHFailedToConnect, SSHBadCommand, SSHProgramFailed
from LIB_SSH import MySSH, SSHFailedToConnect, SSHBadCommand, SSHProgramFailed

# =========================================================================================================================
# ===   ************************************   Diskspace Usage Report    ********************************************   ===
# =========================================================================================================================

MyProgram = StartUp()

MyProgram.LogMsg('.')
MyProgram.LogMsg('. Disk Space Usage Report.')
MyProgram.LogMsg('. ========================')
MyProgram.LogMsg('.')

MyServerList = ['usldynagt11',     'psldynagt11',       'psldynagt12',    'psldynsyn11', \
                'usldynagt21',     'usldynsyn21',       'psldynagt21',    'psldynagt22', 'psldynsyn21', \
                'cab-ltc-praeng',  'cab-ltc-ntp',       'cab-tc2-praeng', 'cab-tc2-ntp', \
                'cab-prod-syslog', 'cab-prod-repo', \
                'cab-uat-amm-db',  'cab-uat-amm-app', \
                'cab-uat-cbs-db',  'cab-uat-cbs-app2',  'cab-uat-cbsig', \
                'cab-uat2-cbs-db', 'cab-uat2-cbs-app2', \
                'cab-prod-dbvc',   'cab-prod-dbvdb', \
                'cab-prod-amm-db', 'cab-prod-amm-app', \
                'cab-prod-cbs-db', 'cab-prod-cbs-app2', 'cab-prod-cbsig', \
                'cab-prod-infral' ]

MyAlert=[]
MySendAlert='NO'

for MyProgram_Hostname in MyServerList:

  # -------------------------------------------------------------------------------------------------------------------------
  # --- Test Connection To Host                                                                                           ---
  # -------------------------------------------------------------------------------------------------------------------------
  MyProgram.LogMsg('.')
  MyProgram.LogMsg('. Connecting To Host : [' + MyProgram_Hostname + '] .....')
  try :
    MySHObject = MySSH(MyProgram_Hostname)
    MySSH_ConnectionGood = MySHObject.RunCommand('hostname')
  except SSHFailedToConnect as MyException:
    raise SSHFailedToConnect()
  except SSHBadCommand as MyException:
    raise SSHBadCommand()
  except SSHProgramFailed as MyException:
    raise SSHProgramFailed()

  # -------------------------------------------------------------------------------------------------------------------------
  # --- Do The Repostory Checks                                                                                           ---
  # -------------------------------------------------------------------------------------------------------------------------
  try :
    MySHObject = MySSH(MyProgram_Hostname)
    MySSH_DFResults = MySHObject.RunCommand('df -hl | grep -v tmpfs')
  except SSHFailedToConnect as MyException:
    raise SSHFailedToConnect()
  except SSHBadCommand as MyException:
    raise SSHBadCommand()
  except SSHProgramFailed as MyException:
    raise SSHProgramFailed()
  else:
    for line in MySSH_DFResults:
      if re.search('^Filesystem', line):
        pass
      else:
        MyDevice, MyFSSize, MyFSUsed, myFSAvail, MyPCTUsed, MyMount = line.split()

        MyPCTUsedNumber=int(MyPCTUsed.replace('%',''))
        if MyPCTUsedNumber > 90 :
           MyStatus='*** FAIL ***'
           MySendAlert='YES'
           MyAlert.append( str('{:20s} :: {:12s}  -  {:15s}  {:4s}  {:10s}  {:10s}  {:10s}'.format(MyProgram_Hostname, MyStatus, MyMount, MyPCTUsed, MyFSSize, MyFSUsed, myFSAvail)) )
        elif MyPCTUsedNumber > 70 :
           MyStatus='*** WARN ***'
           MySendAlert='YES'
           MyAlert.append( str('{:20s} :: {:12s}  -  {:15s}  {:4s}  {:10s}  {:10s}  {:10s}'.format(MyProgram_Hostname, MyStatus, MyMount, MyPCTUsed, MyFSSize, MyFSUsed, myFSAvail)) )
        else:
           MyStatus='***  OK  ***'

        MyLine=str('{:12s}  -  {:15s}  {:50s}  {:4s}  {:10s}  {:10s}  {:10s}'.format(MyStatus, MyMount, MyDevice, MyPCTUsed, MyFSSize, MyFSUsed, myFSAvail))
        MyProgram.LogMsg('.     ' + MyLine )

MyProgram.LogMsg('.')

# -------------------------------------------------------------------------------------------------------------------------
# --- Print Summary Report                                                                                              ---
# -------------------------------------------------------------------------------------------------------------------------
if MySendAlert == 'YES':
  MyProgram.LogMsg('. Generating Report.')
  MyProgram.LogMsg('.')

  MyHeader=str('{:20s} :: {:12s}  -  {:15s}  {:4s}  {:10s}  {:10s}  {:10s}'.format("Hostname", "Status", "Mount", "%PCT", "Size", "Used", "Free"))
  MyProgram.LogMsg('. -> ' + str(MyHeader) )
  MyUnderline=str('{:20s}    {:12s}     {:15s}  {:4s}  {:10s}  {:10s}  {:10s}'.format("--------------------", "------------", "---------------", "----", "----------", "----------", "----------"))
  MyProgram.LogMsg('. -> ' + str(MyUnderline) )

  for MyReportLine in MyAlert:
    MyProgram.LogMsg('. -> ' + str(MyReportLine) )

  MyProgram.LogMsg('.')

# -------------------------------------------------------------------------------------------------------------------------
# --- Program Finished - Terminating Now                                                                                ---
# -------------------------------------------------------------------------------------------------------------------------
MyProgram.LogMsg('.')
MyProgram.LogMsg('. Terminating Program .....')
MyProgram.LogMsg('.')
MyProgram.LogMsg('.')
MyProgram.Terminate()

