#! /usr/bin/python

from LIB_STRT_DoStartUp import StartUp
from LIB_SSH import MySSH, SSHFailedToConnect, SSHBadCommand, SSHProgramFailed
import copy
import datetime
import os

# =========================================================================================================================
# ===   *********************************   Start CBS UAT Environment   *********************************************   ===
# =========================================================================================================================

MyProgram = StartUp()

MyProgram.LogMsg('.')
MyProgram.LogMsg('. START CBS UAT Environment')
MyProgram.LogMsg('. =========================')
MyProgram.LogMsg('.')

MyProgram_Hostname_Database = 'cab-uat-cbs-db'
MyProgram_Hostname_WebLogic = 'cab-uat-cbs-app2'
MyProgram_Hostname_IG = 'cab-uat-cbsig'
MyProgram_Hostname_AMM_Database = 'cab-uat-amm-db'
MyProgram_Hostname_AMM_Apps = 'cab-uat-amm-app'

# -------------------------------------------------------------------------------------------------------------------------
# --- Test Connection To DB Host                                                                                        ---
# -------------------------------------------------------------------------------------------------------------------------
MyProgram.LogMsg('.')
MyProgram.LogMsg('. Connecting To Host : [' + MyProgram_Hostname_Database + '] .....')
try :
  MyProgram_SSH_DB_object = MySSH(MyProgram_Hostname_Database)
  MySSH_ConnectionGood = MyProgram_SSH_DB_object.RunCommand('hostname')
except SSHFailedToConnect as MyException:
  raise SSHFailedToConnect()
except SSHBadCommand as MyException:
  raise SSHBadCommand()
except SSHProgramFailed as MyException:
  raise SSHProgramFailed()

# -------------------------------------------------------------------------------------------------------------------------
# --- Test Connection To WebLogic Host                                                                                  ---
# -------------------------------------------------------------------------------------------------------------------------
MyProgram.LogMsg('.')
MyProgram.LogMsg('. Connecting To Host : [' + MyProgram_Hostname_WebLogic + '] .....')
try :
  MyProgram_SSH_APP_object = MySSH(MyProgram_Hostname_WebLogic)
  MySSH_ConnectionGood = MyProgram_SSH_APP_object.RunCommand('hostname')
except SSHFailedToConnect as MyException:
  raise SSHFailedToConnect()
except SSHBadCommand as MyException:
  raise SSHBadCommand()
except SSHProgramFailed as MyException:
  raise SSHProgramFailed()

# -------------------------------------------------------------------------------------------------------------------------
# --- Test Connection To IG Host                                                                                        ---
# -------------------------------------------------------------------------------------------------------------------------
MyProgram.LogMsg('.')
MyProgram.LogMsg('. Connecting To Host : [' + MyProgram_Hostname_IG + '] .....')
try :
  MyProgram_SSH_IG_object = MySSH(MyProgram_Hostname_IG)
  MySSH_ConnectionGood = MyProgram_SSH_IG_object.RunCommand('hostname')
except SSHFailedToConnect as MyException:
  raise SSHFailedToConnect()
except SSHBadCommand as MyException:
  raise SSHBadCommand()
except SSHProgramFailed as MyException:
  raise SSHProgramFailed()

# -------------------------------------------------------------------------------------------------------------------------
# --- Test Connection To AMM DB Host                                                                                    ---
# -------------------------------------------------------------------------------------------------------------------------
MyProgram.LogMsg('.')
MyProgram.LogMsg('. Connecting To Host : [' + MyProgram_Hostname_AMM_Database + '] .....')
try :
  MyProgram_SSH_AMMDB_object = MySSH(MyProgram_Hostname_AMM_Database)
  MySSH_ConnectionGood = MyProgram_SSH_IG_object.RunCommand('hostname')
except SSHFailedToConnect as MyException:
  raise SSHFailedToConnect()
except SSHBadCommand as MyException:
  raise SSHBadCommand()
except SSHProgramFailed as MyException:
  raise SSHProgramFailed()

# -------------------------------------------------------------------------------------------------------------------------
# --- Test Connection To AMM Application Server                                                                         ---
# -------------------------------------------------------------------------------------------------------------------------
MyProgram.LogMsg('.')
MyProgram.LogMsg('. Connecting To Host : [' + MyProgram_Hostname_AMM_Apps + '] .....')
try :
  MyProgram_SSH_AMMAPP_object = MySSH(MyProgram_Hostname_AMM_Apps)
  MySSH_ConnectionGood = MyProgram_SSH_IG_object.RunCommand('hostname')
except SSHFailedToConnect as MyException:
  raise SSHFailedToConnect()
except SSHBadCommand as MyException:
  raise SSHBadCommand()
except SSHProgramFailed as MyException:
  raise SSHProgramFailed()


# -------------------------------------------------------------------------------------------------------------------------
# --- Start AMM Application Services                                                                                    ---
# -------------------------------------------------------------------------------------------------------------------------
MyProgram.LogMsg('.')
MyProgram.LogMsg('. Starting AMM Application Service(s) .....')

# -------------------------------------------------------------------------------------------------------------------------
# --- Stop AMM Application Services                                                                                     ---
# -------------------------------------------------------------------------------------------------------------------------
MyProgram.LogMsg('.')
MyProgram.LogMsg('. Starting AMM Application Service(s) .....')

MyProgram.LogMsg('.   Starting JBOSS Service obut1 - CUSTOMER and ADMIN .....')
try :
  MyProgram_Stop_WebLogic = MyProgram_SSH_AMMAPP_object.RunCommand("sudo -u jboss sh -c '/dataarea1/app/scripts/AMM_start_ALL.sh'")
except SSHFailedToConnect as MyException:
  raise SSHFailedToConnect()
except SSHBadCommand as MyException:
  raise SSHBadCommand()
except SSHProgramFailed as MyException:
  raise SSHProgramFailed()
else:
  for line in MyProgram_Stop_WebLogic:
    MyProgram.LogMsg('.   -> ' + str(line))

MyProgram.LogMsg('.   Starting JBOSS Service obut3 - CUSTOMER and ADMIN .....')
try :
  MyProgram_Stop_WebLogic = MyProgram_SSH_AMMAPP_object.RunCommand("sudo -u jboss3 sh -c '/dataarea1/app/scripts/AMM_start_ALL3.sh'")
except SSHFailedToConnect as MyException:
  raise SSHFailedToConnect()
except SSHBadCommand as MyException:
  raise SSHBadCommand()
except SSHProgramFailed as MyException:
  raise SSHProgramFailed()
else:
  for line in MyProgram_Stop_WebLogic:
    MyProgram.LogMsg('.   -> ' + str(line))

# -------------------------------------------------------------------------------------------------------------------------
# --- Start DbVisit Standby Database DR - AMM                                                                           ---
# -------------------------------------------------------------------------------------------------------------------------
MyProgram.LogMsg('.')
MyProgram.LogMsg('. Starting AMM DbVisit Standby Database(s)')

MyProgram.LogMsg('.   Starting AMM DbVisit Manager')
try :
  MyProgram_Stop_Database = MyProgram_SSH_AMMDB_object.RunCommand("sudo /usr/dbvisit/standbymp/bin/dbvagentmanager service start")
except SSHFailedToConnect as MyException:
  raise SSHFailedToConnect()
except SSHBadCommand as MyException:
  raise SSHBadCommand()
except SSHProgramFailed as MyException:
  raise SSHProgramFailed()
else:
  for line in MyProgram_Stop_Database:
    MyProgram.LogMsg('.   -> ' + str(line))

MyProgram.LogMsg('.   Starting AMM DbVisit Standby Database - oblv')
try :
  MyProgram_Stop_Database = MyProgram_SSH_AMMDB_object.RunCommand("sudo -u oracle sh -c '/home/oracle/.bash_profile ; /usr/dbvisit/standbymp/oracle/dbvctl -d oblv -o start'")
except SSHFailedToConnect as MyException:
  raise SSHFailedToConnect()
except SSHBadCommand as MyException:
  raise SSHBadCommand()
except SSHProgramFailed as MyException:
  raise SSHProgramFailed()
else:
  for line in MyProgram_Stop_Database:
    MyProgram.LogMsg('.   -> ' + str(line))

MyProgram.LogMsg('.   Starting AMM DbVisit Standby Database - oblvuat')
try :
  MyProgram_Stop_Database = MyProgram_SSH_AMMDB_object.RunCommand("sudo -u oracle sh -c '/home/oracle/.bash_profile ; /usr/dbvisit/standbymp/oracle/dbvctl -d oblvuat -o start'")
except SSHFailedToConnect as MyException:
  raise SSHFailedToConnect()
except SSHBadCommand as MyException:
  raise SSHBadCommand()
except SSHProgramFailed as MyException:
  raise SSHProgramFailed()
else:
  for line in MyProgram_Stop_Database:
    MyProgram.LogMsg('.   -> ' + str(line))


# -------------------------------------------------------------------------------------------------------------------------
# --- Start DbVisit Standby Database DR - CBS                                                                           ---
# -------------------------------------------------------------------------------------------------------------------------
MyProgram.LogMsg('.')
MyProgram.LogMsg('. Starting CBS DbVisit Standby Database(s)')

MyProgram.LogMsg('.   Starting CBS DbVisit Manager')
try :
  MyProgram_Stop_Database = MyProgram_SSH_DB_object.RunCommand("sudo /usr/dbvisit/standbymp/bin/dbvagentmanager service start")
except SSHFailedToConnect as MyException:
  raise SSHFailedToConnect()
except SSHBadCommand as MyException:
  raise SSHBadCommand()
except SSHProgramFailed as MyException:
  raise SSHProgramFailed()
else:
  for line in MyProgram_Stop_Database:
    MyProgram.LogMsg('.   -> ' + str(line))

MyProgram.LogMsg('.   Starting CBS DbVisit Standby Database - bklv')
try :
  MyProgram_Stop_Database = MyProgram_SSH_DB_object.RunCommand("sudo -u oracle sh -c '/home/oracle/.bash_profile ; /usr/dbvisit/standbymp/oracle/dbvctl -d bklv -o start'")
except SSHFailedToConnect as MyException:
  raise SSHFailedToConnect()
except SSHBadCommand as MyException:
  raise SSHBadCommand()
except SSHProgramFailed as MyException:
  raise SSHProgramFailed()
else:
  for line in MyProgram_Stop_Database:
    MyProgram.LogMsg('.   -> ' + str(line))

MyProgram.LogMsg('.   Starting CBS DbVisit Standby Database - bklvuat')
try :
  MyProgram_Stop_Database = MyProgram_SSH_DB_object.RunCommand("sudo -u oracle sh -c '/home/oracle/.bash_profile ; /usr/dbvisit/standbymp/oracle/dbvctl -d bklvuat -o start'")
except SSHFailedToConnect as MyException:
  raise SSHFailedToConnect()
except SSHBadCommand as MyException:
  raise SSHBadCommand()
except SSHProgramFailed as MyException:
  raise SSHProgramFailed()
else:
  for line in MyProgram_Stop_Database:
    MyProgram.LogMsg('.   -> ' + str(line))


# -------------------------------------------------------------------------------------------------------------------------
# --- Completed Message                                                                                                 ---
# -------------------------------------------------------------------------------------------------------------------------
MyProgram.LogMsg('.')
MyProgram.LogMsg('. Started CBS WebLogic, Database; AMM JBOSS, Database, IG Services and DbVisit')

# -------------------------------------------------------------------------------------------------------------------------
# --- Program Finished - Terminating Now                                                                                ---
# -------------------------------------------------------------------------------------------------------------------------
MyProgram.LogMsg('.')
MyProgram.LogMsg('. Terminating Program .....')
MyProgram.LogMsg('.')
MyProgram.LogMsg('.')
MyProgram.Terminate()
